export default {
  'FOOD': [
    'cake',
    'cookie',
    'curry rice',
    'hamburger',
    'Omelette',
    'pizza',
    'ramen',
    'salad',
    'sandwich',
    'spaghetti',
    'steak',
    'stew',
    'sushi',
  ],
  'SPORTS': [
    'Archery',
    'badminton',
    'baseball',
    'basketball',
    'Billiards',
    'Bowling',
    'boxing',
    'Canoe',
    'Clay shooting',
    'Climbing',
    'curling',
    'Darts',
    'diving',
    'Dodgeball',
    'fencing',
    'Flying disc · Frisbee',
    'Football',
    'Gateball',
    'golf',
    'Gymnastics',
    'Hammer throwing',
    'Hockey · Ice Hockey',
    'Horse riding',
    'Hurdle run',
    'judo',
    'Jump rope',
    'karate',
    'marathon',
    'Pole vault',
    'relay',
    'Road race / bicycle race',
    'rock climbing',
    'Roller skate',
    'rugby',
    'skate',
    'skateboard',
    'Ski',
    'sky diving',
    'snow board',
    'Sumo',
    'surfing',
    'swimming',
    'synchronized swimming',
    'Table tennis',
    'tennis',
    'volleyball',
    'Weightlifting',
    'wrestling',
  ],
  'ANIMAL': [
    'bat',
    'bear',
    'buffalo',
    'camel',
    'cat',
    'cow',
    'deer',
    'dog',
    'donkey',
    'elephant',
    'fox',
    'giraffe',
    'goat',
    'gorilla',
    'hamster',
    'hippopotamus',
    'horse',
    'jaguar',
    'kangaroo',
    'koala',
    'leopard',
    'lion',
    'mole',
    'monkey',
    'mouse',
    'panda',
    'pig',
    'polar bear',
    'rabbit',
    'raccoon',
    'rat',
    'reindeer',
    'rhinoceros',
    'sheep',
    'skunk',
    'squirrel',
    'tiger',
    'wild boar',
    'wolf',
    'zebra',
  ],
  'TALE': [
    'Cinderella',
    'The Tortoise and the Hare',
    'Little Red Riding Hood',
    'Snow White',
    'The Ugly Duckling',
    'The Ant and the Grasshopper',
    'The Boy Who Cried Wolf',
    'Thumbelina',
    'The North Wind and the Sun',
    'Mercury and the Woodman',
    'The Three Little Pigs',
    'Jack and the Beanstalk',
    'The Little Mermaid',
    'Sleeping Beauty',
    'The Emperor\'s New Clothes',
    'The Little Match Girl',
    'The Ugly Duckling',
    'Peter Pan',
    'Rapunzel',
  ],
};
