export default {
  'FOOD': [
    'cake',
    'cookie',
    'curry rice',
    'hamburger',
    'Omelette',
    'pizza',
    'ramen',
    'salad',
    'sandwich',
    'spaghetti',
    'steak',
    'stew',
    'sushi',
  ],
  'SPORTS': [
    'Archery',
    'badminton',
    'baseball',
    'basketball',
    'Billiards',
    'Bowling',
    'boxing',
    'Canoe',
    'Clay shooting',
    'Climbing',
    'curling',
    'Darts',
    'diving',
    'Dodgeball',
    'fencing',
    'Flying disc · Frisbee',
    'Football',
    'Gateball',
    'golf',
    'Gymnastics',
    'Hammer throwing',
    'Hockey · Ice Hockey',
    'Horse riding',
    'Hurdle run',
    'judo',
    'Jump rope',
    'karate',
    'marathon',
    'Pole vault',
    'relay',
    'Road race / bicycle race',
    'rock climbing',
    'Roller skate',
    'rugby',
    'skate',
    'skateboard',
    'Ski',
    'sky diving',
    'snow board',
    'Sumo',
    'surfing',
    'swimming',
    'synchronized swimming',
    'Table tennis',
    'tennis',
    'volleyball',
    'Weightlifting',
    'wrestling',
  ],
  'ANIMAL': [
    'animal',
    'bat',
    'bear',
    'buffalo',
    'camel',
    'cat',
    'cow',
    'deer',
    'dog',
    'donkey',
    'elephant',
    'fox',
    'giraffe',
    'goat',
    'gorilla',
    'hamster',
    'hippopotamus',
    'horse',
    'jaguar',
    'kangaroo',
    'koala',
    'leopard',
    'lion',
    'mole',
    'monkey',
    'mouse',
    'panda',
    'pig',
    'polar bear',
    'rabbit',
    'raccoon',
    'raccoon',
    'rat',
    'reindeer',
    'rhinoceros',
    'sheep',
    'skunk',
    'squirrel',
    'tiger',
    'wild boar',
    'wolf',
    'zebra',
  ],
  // 'TALE': [
  //   'Cinderella',
  // ],
  // 'Event': [
  //   'Christmas',
  // ],
};
